run:
  timeout: 10m
  deadline: 2m
  skip-dirs:
    - scripts

linter-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 12.0
  maligned:
    suggest-new: true
  goconst:
    min-len: 3.0
    min-occurrences: 3.0
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - tparallel
    - paralleltest
    - exhaustivestruct
    - forcetypeassert
    - varnamelen
issues:
  exclude-rules:
    - path: _test\.go
      text: "err113: do not define dynamic errors, use wrapped static errors instead"
    - path: _test\.go
      text: "error returned from external package is unwrapped"
    - path: _test\.go
      text: "type assertion must be checked"
    - path: provider_test.go
      text: "testAccProvider[s]* is a global variable"
    - path: provider_test.go
      text: "don't use `init` function"
    - path: resource_sendgrid_api_key.go
      text: "Consider preallocating `scopes`"
